POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "min",
  "password": "minnan35"
}

> {% client.global.set("admin_token", response.body.data.jwtToken); %}

###
POST {{baseUrl}}/api/getAllLinkList
Content-Type: application/json
Authorization: {{admin_token}}

{}