POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "Minnan",
  "password": "minnan35"
}

> {% client.global.set("admin_token", "Bearer " + response.body.data.jwtToken); %}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
  "username": "aaa",
  "password": "min107"
}

###
POST {{baseUrl}}/manager/getImageList
Content-Type: application/json
Authorization: {{admin_token}}

{}

###
POST {{baseUrl}}/manager/createUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJTdWJqZWN0IjoiTWlubmFuIiwiSWQiOjEsIkV4cGlyZXNBdCI6MTYyMDUzMzAzOTczMCwiSXNzdWVkQXQiOjE2MjA0NDY2Mzk3MzB9.vIZ4rPB8XCPGMaArre8b4HPRrMpiMPFWjKKu_WSpWkmBwCxqUN1uJ9OMpTCv1o0WZmL-ASaSlFjBJ8STtesaqw

{
  "username": "chf",
  "password": "chf123",
  "nickName": "chf"
}

###
POST {{baseUrl}}/api/getIntroduction
Content-Type: application/json
Authorization: {{admin_token}}

{}

###
POST {{baseUrl}}/api/getImageList
Content-Type: application/json
Authorization: {{admin_token}}

{}

###
POST {{baseUrl}}/api/downloadTools
Content-Type: application/json
Authorization: {{admin_token}}

{
  "id":1
}